// Temporarily disable real Supabase calls - UI only mode
// This file is automatically generated. Do not edit it directly.
// import { createClient } from '@supabase/supabase-js';
// import type { Database } from './types';

// const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
// const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
//   auth: {
//     storage: localStorage,
//     persistSession: true,
//     autoRefreshToken: true,
//   }
// });

// Mock Supabase client for UI-only mode
export const supabase = {
  auth: {
    signUp: async (options?: any) => {
      // Simulate successful signup
      console.log('Mock signup called with:', options);
      return Promise.resolve({ 
        data: { 
          user: { 
            id: 'mock-user-id', 
            email: options?.email || 'user@example.com',
            user_metadata: options?.options?.data || {}
          } 
        }, 
        error: null 
      });
    },
    signInWithOAuth: async (options?: any) => {
      // Simulate successful OAuth
      console.log('Mock OAuth called with:', options);
      return Promise.resolve({ error: null });
    },
    getUser: async () => {
      // Simulate no user logged in
      return Promise.resolve({ data: { user: null }, error: null });
    }
  }
};